server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Caché larga para archivos con hash en el nombre; index.html siempre fresco
  location /assets/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
  }
  location / {
    add_header Cache-Control "no-cache";
    try_files $uri $uri/ /index.html;
  }
}
